import os
import subprocess
import logging

logger = logging.getLogger(__name__)

class UKIManager:
    """Manages systemd-boot and Unified Kernel Image (UKI) generation via mkinitcpio."""
    
    def __init__(self, target_mount: str):
        self.target = target_mount
        self.esp_path = os.path.join(self.target, "efi")

    def install_systemd_boot(self) -> bool:
        """Installs systemd-boot to the EFI system partition."""
        logger.info("Installing systemd-boot...")
        try:
            subprocess.run(["arch-chroot", self.target, "bootctl", "install"], check=True)
            return True
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to install systemd-boot: {e}")
            return False

    def configure_mkinitcpio_uki(self, kernel: str = "linux-zen", ucode: str = ""):
        """Configures mkinitcpio to generate a UKI directly to the ESP."""
        logger.info(f"Configuring UKI generation for {kernel}...")
        
        # Write the mkinitcpio preset for UKI
        preset_content = f"""
# mkinitcpio preset generated by CavrixInstall
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="/boot/vmlinuz-{kernel}"

PRESETS=('default' 'fallback')

default_uki="/efi/EFI/Linux/cavrixos-{kernel}.efi"
default_options=""

fallback_uki="/efi/EFI/Linux/cavrixos-{kernel}-fallback.efi"
fallback_options="-S autodetect"
"""
        preset_path = os.path.join(self.target, f"etc/mkinitcpio.d/{kernel}.preset")
        os.makedirs(os.path.dirname(preset_path), exist_ok=True)
        
        with open(preset_path, "w") as f:
            f.write(preset_content.strip())
            
        # Ensure the Linux directory exists on the ESP
        os.makedirs(os.path.join(self.esp_path, "EFI/Linux"), exist_ok=True)

    def generate_ukis(self) -> bool:
        """Runs mkinitcpio to generate the configured UKIs."""
        logger.info("Generating Unified Kernel Images...")
        try:
            subprocess.run(["arch-chroot", self.target, "mkinitcpio", "-P"], check=True)
            return True
        except subprocess.CalledProcessError as e:
            logger.error(f"UKI generation failed: {e}")
            return False
