import os
import subprocess
import logging

logger = logging.getLogger(__name__)

class UKIManager:
    """
    Manages systemd-boot installation, config generation, and Unified Kernel Image (UKI) 
    compilation via mkinitcpio for production UEFI boot.
    """
    
    def __init__(self, target_mount: str = "/mnt"):
        self.target = target_mount
        self.esp_path = os.path.join(self.target, "efi")

    def _run_cmd(self, cmd: list) -> bool:
        try:
            logger.debug(f"Executing: {' '.join(cmd)}")
            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            return True
        except subprocess.CalledProcessError as e:
            logger.error(f"Command failed: {' '.join(cmd)}")
            logger.error(f"Error output: {e.stderr.decode('utf-8').strip()}")
            return False

    def install_systemd_boot(self) -> bool:
        """Installs systemd-boot to the ESP."""
        logger.info("Installing systemd-boot to EFI partition...")
        # Need to ensure the EFI variables can be written if booted in EFI mode
        cmd = ["arch-chroot", self.target, "bootctl", "install", "--esp-path=/efi"]
        return self._run_cmd(cmd)

    def write_loader_conf(self) -> bool:
        """Writes the global systemd-boot loader.conf."""
        logger.info("Writing loader.conf...")
        loader_path = os.path.join(self.esp_path, "loader/loader.conf")
        os.makedirs(os.path.dirname(loader_path), exist_ok=True)
        
        content = """default @saved
timeout 3
console-mode max
editor no
"""
        try:
            with open(loader_path, "w") as f:
                f.write(content)
            return True
        except Exception as e:
            logger.error(f"Failed to write loader.conf: {e}")
            return False

    def configure_mkinitcpio_uki(self, kernel: str = "linux-zen") -> bool:
        """Configures mkinitcpio to generate a UKI directly to the ESP."""
        logger.info(f"Configuring UKI generation preset for {kernel}...")
        
        preset_content = f"""# mkinitcpio preset generated by CavrixInstall
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="/boot/vmlinuz-{kernel}"

PRESETS=('default')

default_uki="/efi/EFI/Linux/cavrixos-{kernel}.efi"
# Kernel command line is embedded into the UKI
default_options="--splash /usr/share/systemd/bootctl/splash-cavrix.bmp"
"""
        preset_path = os.path.join(self.target, f"etc/mkinitcpio.d/{kernel}.preset")
        os.makedirs(os.path.dirname(preset_path), exist_ok=True)
        
        try:
            with open(preset_path, "w") as f:
                f.write(preset_content.strip())
                
            # Ensure the Linux directory exists on the ESP
            os.makedirs(os.path.join(self.esp_path, "EFI/Linux"), exist_ok=True)
            return True
        except Exception as e:
            logger.error(f"Failed to write preset: {e}")
            return False

    def generate_cmdline(self, root_uuid: str, is_encrypted: bool = False) -> bool:
        """Generates the kernel command line configuration file for UKI embedding."""
        logger.info("Generating kernel cmdline...")
        cmdline_path = os.path.join(self.target, "etc/kernel/cmdline")
        os.makedirs(os.path.dirname(cmdline_path), exist_ok=True)
        
        cmdline = f"root=UUID={root_uuid} rw rootflags=subvol=@ quiet splash loglevel=3 "
        if is_encrypted:
            cmdline += f"cryptdevice=UUID={root_uuid}:cavrix_crypt "
            
        try:
            with open(cmdline_path, "w") as f:
                f.write(cmdline.strip())
            return True
        except Exception as e:
            logger.error(f"Failed to write cmdline: {e}")
            return False

    def generate_ukis(self) -> bool:
        """Runs mkinitcpio to compile the UKI binaries."""
        logger.info("Compiling Unified Kernel Images (This will take a moment)...")
        return self._run_cmd(["arch-chroot", self.target, "mkinitcpio", "-P"])
