name: Build ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Packages, Repo, and ISO in Arch Container
      run: |
        docker run --privileged -v ${{ github.workspace }}:/workspace -w /workspace archlinux:base-devel bash -c "pacman-key --init && pacman --noconfirm -Sy archlinux-keyring && pacman --noconfirm -S archiso git make sudo && useradd -m builduser && echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && chown -R builduser:builduser /workspace && su builduser -c 'make packages repo' && make iso" > build.log 2>&1 || (
          log_content=$(tail -n 100 build.log | jq -Rs .)
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues -d "{\"title\":\"Build Failed Log\",\"body\":$log_content}"
          exit 1
        )


    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CavrixOS-Live-ISO
        path: build/*.iso
